# Root logger
log4j.rootLogger=INFO, Console, File

# Console appender
log4j.appender.Console=org.apache.log4j.ConsoleAppender
log4j.appender.Console.Target=System.out
log4j.appender.Console.layout=org.apache.log4j.PatternLayout
log4j.appender.Console.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

# Rolling file appender
log4j.appender.File=org.apache.log4j.RollingFileAppender
log4j.appender.File.File=${catalina.home}/logs/line-interface/line-interface.log
log4j.appender.File.MaxFileSize=5MB
log4j.appender.File.MaxBackupIndex=10
log4j.appender.File.layout=org.apache.log4j.PatternLayout
log4j.appender.File.layout.ConversionPattern=%d{dd/MM/yyyy HH:mm:ss,SSS} %-5p %c{1}:%L - %m%n
